# Site settings
title: ansidev.github.io
email: ansidev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog hosted on GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ansidev.github.io" # the base hostname & protocol for your site
twitter_username: ansidev
github_username:  ansidev

# Build settings
markdown: kramdown
# markdown: redcarpet
sass:
    sass_dir: _sass
